FROM intel/oneapi-runtime

RUN apt-key adv --fetch-key https://repo.arrayfire.com/GPG-PUB-KEY-ARRAYFIRE-2020.PUB
RUN echo "deb [arch=amd64] https://repo.arrayfire.com/debian all main" > /etc/apt/sources.list.d/arrayfire.list
RUN apt update
RUN apt install -y arrayfire-cpu3-dev
gpryor@a770:github-codespaces- > cat Dockerfile 
FROM intel/oneapi-runtime

RUN apt-key adv --fetch-key https://repo.arrayfire.com/GPG-PUB-KEY-ARRAYFIRE-2020.PUB
RUN echo "deb [arch=amd64] https://repo.arrayfire.com/debian all main" > /etc/apt/sources.list.d/arrayfire.list
RUN apt update
RUN apt install -y arrayfire-cpu3-dev
